MBTips/FE-MBTips

index.html
package-lock.json
package.json
postcss.config.js
src/App.tsx
src/components/LoginButton.tsx
src/index.css
tailwind.config.js
vite.config.ts

랜딩페이지 우측 상단에 렌더링 되는 로그인 버튼 단순 ui 작업입니다.

Feat: LoginButton ui 컴포넌트 완성

---

.github/workflows/ci.yml

- dev 브랜치에 push 될 때마다 자동으로 buiild error 잡아주는 ci.yml 코드입니다.
```
name: 빌드 자동화
on:
push:
branches:
- dev
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2
- name: Set up Node.js (또는 다른 언어 환경)
uses: actions/setup-node@v2
with:
node-version: '20'  
- name: Install dependencies
run: npm install  
- name: Run build
run: npm run build  
```

Feat: Create Ci.yml

---

src/components/IntroGuide.tsx

#29 이슈에 적어두었습니다
- 작업한 내용은 이전 PR과 동일하고 review도 반영했습니다.
- git이 꼬여 히스토리가 모두 섞이는 이슈가 발생했습니다... 해당 브랜치에서 해결하기 어려워 보여 브랜치를 처음부터 다시 만드는 방법을 선택했습니다 ㅎㅎ;

Feat: IntroGuide 컴포넌트 구현

---

src/components/ChatMessage.tsx

- chat message component 개발 (공통 컴포넌트)
- #45 
- 없음

feat: chat message component 개발

---

src/components/button/ChatStartButton.tsx
src/index.css

- breakpoint를 피그마 명시대로 커스텀 한 작업입니다. #53 
- 사용 예시는 다음과 같습니다.
className : sm:w-[345px]    // sm일 때(345px~375px일 때) width는 375px

chore: index.css에 breakpoint 추가

---

package-lock.json
package.json
src/App.tsx
src/api/axios.ts
src/components/TermsAndPrivacy.tsx
src/components/button/KakaoLoginButton.tsx
src/components/modal/TermsAndPrivacyModal.tsx
src/pages/KaKaoLogin.tsx
src/pages/Login.tsx
src/store/useAuthStore.ts

- url로 받은 kakao 인가 코드를 params로 실어 /api/kako/login api로 GET 요청
-  HTTP 요청이 성사되었다면 받은 res.data로 accessToken을 받음
-  accessToken이 잘 받아졌다면 로컬스토리지에 isLoggedIn -> true, accessToken을 저장함. ( 이 부분은 useAuthStore의 login()이 수행)
- 홈페이지로 사용자를 리다이렉트 시킴 
1. 환경변수(.env.local) 전역 디렉토리에 똑같이 만들어주세요!
```
VITE_API_BASE_URL=http://34.47.114.108:8080/
VITE_KAKAO_REST_API_KEY=3e5cfa29037d1bd11eb5448f9b298bfe
VITE_KAKAO_REDIRECT_URI=http://34.47.114.108:8080/api/kakao/login
```
- 접두어에 반드시 "VITE_" 라는 문자열을 넣어주어야 한답니다.
- 사용할 때에는 "import.meta.env.VITE_KAKAO_REST_API_KEY"오 같이 사용해주면 됩니다. import.meta.env. 라는 접두어가 붙는 것이 특징입니다.
2. 배포환경에서 테스트해야 하는데 아직 ci/cd PR이 merge 되지 않은 상황이라 테스트까지는 하지 못했습니다. 버그의 여지가 있습니다.

Feature/로그인 페이지 기능 개발

---

src/App.tsx
src/components/CenteredLayout.tsx

fix: 전체 레이아웃 내 background color 적용

---

.github/workflows/ci.yml
Dockerfile
package.json
src/components/Indicator.tsx
vite.config.ts

- dev에 Feat/cicd 적용 작업
- local dev에 Fe-MBtips의 Feat/cicd를 pull 받아온 후 conflict 해결
- 없음
- dev, prod mode build 확인 완료

Feat/cicd 브랜치 -> Dev 브랜치 반영 작업

---

src/pages/SelectInfo.tsx

fix: fast friend api 전달 시 interests값 추가

---

src/pages/Content.tsx

feat: content api 연동 작업

---

vite.config.ts

feat: 파일이 존재할 때만 fs.readFileSync를 실행하도록 설정

---

vite.config.ts

fix: https 조건 수정

---

src/components/ToastMessage.tsx
src/pages/SelectInfo.tsx

feat: ToastMessage 공통 컴포넌트 개발 및 Select Info 내 ToastMessage 적용 

---

.github/workflows/ci.yml
src/libs/analytics.ts
vite.config.ts

fix: hmr 설정 변경

---

src/App.tsx
src/libs/analytics.ts

fix: add log for ga4

---

.github/workflows/ci.yml
vite.config.ts

feat: github actions build 단계에 prod 명시 및 로그 추가

---

src/pages/Content.tsx

fix: content api 절대경로로 수정

---

.github/workflows/ci.yml
vite.config.ts

fix: ci 설정 수정

---

.github/workflows/ci.yml
src/libs/analytics.ts

fix: ci 수정

---

.github/workflows/ci.yml

fix: ci 설정

---

src/pages/SelectInfo.tsx

fix: Fast Friend API 필드 수정

---

vite.config.ts

fix: hmr 설정

---

src/App.tsx
src/pages/MyInfo.tsx

feat: 내 정보 화면 리스트 개발

---

src/components/ChatAction.tsx
src/components/ChatActionBar.tsx
src/components/ChatMessage.tsx
src/components/IntroGuide.tsx
src/components/input/MessageInput.tsx
src/pages/Chat.tsx
src/pages/SelectInfo.tsx

- #147 
- 하단 + 버튼 클릭 시 대화주제 추천 포함 3가지 컨텐츠 표시 필요
- API 연동 필요
- 팝업(Alert.tsx) 적용 필요

feat: chat room UI 개발

---

.github/workflows/ci.yml
vite.config.ts

fix: remove logs

---

.github/workflows/ci.yml
vite.config.ts

feat: cicd 설정

---

src/App.tsx
src/libs/analytics.ts
src/pages/Content.tsx

fix: GA4 설정 변경

---

.github/workflows/ci.yml

Conflict 해결

---

src/pages/Chat.tsx
src/pages/SelectInfo.tsx

- #160 
- 친구 저장(Virtual Friend)의 경우 chat history 불러오기 작업 필요
- 채팅 나가기 팝업 추가 필요

feat: chat api 연동 작업

---

src/components/ChatActionBar.tsx
src/components/button/ToggleChatTipsButton.tsx
src/components/tips/TipsMenu.tsx
src/components/tips/TipsMenuContainer.tsx
src/index.css
src/pages/Chat.tsx
vite.config.ts

- 이슈에 적어둔 것과 동일합니다.
https://github.com/user-attachments/assets/14ba4336-0836-47d8-880a-bc8a2bc4c750

feat: ToggleChatTIpsButton 열고 닫히는 기능 구현 완료

---

src/pages/Login.tsx

- 이슈에 적어둔 것과 동일합니다.
- 없음
https://github.com/user-attachments/assets/e396a76f-d02e-41c4-86b8-c0f786929bb8

style: TermsAndPrivacyt 감싸는 div에 pb-4 추가

---

src/pages/Chat.tsx

fix: chat icon 이미지 비율 유지

---

src/pages/Chat.tsx

fix: 채팅 input 하단 고정

---

.github/workflows/cicd.yml

fix: cicd.yml -> 환경변수 생성하는 로직 추가

---

src/components/button/KakaoLoginButton.tsx

chore: DEVELOP -> DEVELOPE 오타 수정

---

src/pages/MyInfo.tsx

feat: 로그인 시에만 my info 접근 가능하도록 조건 추가

---

src/pages/SelectInfo.tsx

fix: select info 화면 내 공유하기 버튼 제거

---

src/pages/Content.tsx

feat: 일반 콘텐츠 header 문구 변경

---

src/pages/Content.tsx

fix: 일반 콘텐츠의 navigate 수정

---

src/App.tsx

chore: og:image content 값 수정

---

src/components/Profile.tsx
src/components/header/MainHeader.tsx
src/components/header/SubHeader.tsx

- React에서는 **/icon/arrow_left.svg**처럼 슬래시(/)로 시작하는 경로를 사용하면, 자동으로 public 폴더 기준으로 이미지를 찾는다고 합니다.
- 없음

fix: img src가 "/public"으로 시작하는 코드 모두 삭제

---

src/components/button/FormButton.tsx
src/pages/SelectInfo.tsx

feat: 친구저장 폼 항목 변경

---

src/App.tsx
src/components/Profile.tsx
src/pages/SelectInfo.tsx

- #288 
- 없음
https://github.com/user-attachments/assets/6748d63a-9e69-4987-9dbb-fc3e2de7b020

Feat  오픈채팅 관련 기능 ga 추가
